# Generated by Django 5.0.2 on 2024-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_position_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='party_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
