# Generated by Django 5.0.2 on 2024-02-27 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_position_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='party_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
